### ISSUE TITLE
ctPointLabels is not defined

### ISSUE THREAD

**Issue by juanomoran** [gionkunz/chartist-plugin-pointlabels#1]
Hi, I've found chartist to be an excellent tool. I customized my charts to a great extent by modifying the css file. 

However, when I try to get any of the proposed plugins that you posted, I cannot get the to work. I'm srry if this is a newbie question, but that's what I'm. What I've tried so far are the following options:

OPTION A:
1) download the chartist-plugin-ctpointlabels.js and saved it in the "chartist/dist" folder, right alongside chartist.js and chartist.css which I know are working.
2) Added the plugin description in the configuration options of the chartist.Line call

```
        $scope.config = {
              high: 15,
              low: 0,
              showArea: true,
              showLine: true,
              showPoint: true,
              fullWidth:true,
              axisY: {
                 showLabel: false,
                 showGrid: false,
                 offset: 5
              },
              axisX: {
                showLabel: false,
                showGrid: false
              },
              plugins: [
                ctPointLabels({
                  textAnchor: 'middle'
                }),
                ],

        };
```

3) Result: All I get is an error stating that ctPointLabels is not defined: " ReferenceError: ctPointLabels is not defined"

OPTION B:
1) download the chartist-plugin-ctpointlabels.js, copied its code and placed it whitin chartis.js (on the same level as @module Chartist.Base - line 1153 or Chartist.Class - line 1044) o even at the very begging of the file (line 1).
2) and 3) same as OPTION A

It's worth noting that the chart is working fine with the original config options (with the the " plugins" section commented). The original working options are: 

$scope.config = {
                  high: maxVal,
                  low: 0,
                  showArea: true,
                  showLine: true,
                  showPoint: showPoints,
                  fullWidth:true,
                  axisY: {
                     showLabel: false,
                     showGrid: false,
                     offset: 5
                  },
                  axisX: {
                    showLabel: false,
                    showGrid: false
                  }
                  // ,
                  // plugins: [
                  //   ctPointLabels({
                  //     textAnchor: 'middle'
                  //   }),
                //  ],

```
        };
```

Thanks for any help or guide on how to properly setup the workspace for plugins (I checked the chartistjs plugin section, but I couldn't find a solution)

**Comment by gionkunz** [comment]
Hey there. Thanks for the detailed issue! Actually youre doing it right with option A but the example is wrong in the readme! It should be Chartist.plugins.ctPointLabels and not ctPointLabels.

**Comment by gionkunz** [comment]
Ill update the readme

**Comment by gionkunz** [comment]
You didnt mention that youve included the script of the plugin in your html. So in case youve missed that youd also need to do this.

**Comment by juanomoran** [comment]
Hi, thanks for the prompt reply. I had included the script in the html, so it may be the naming of the plugin. Later today I'll try and let you know if it works.

**Comment by juanomoran** [comment]
Great! It worked like a charm! thanks! I will post some other questions on the main library repository later. Thanks for the awesome work!

**Comment by juanomoran** [comment]
Ok, just to let you know. Your code is incredibly flexible. I just wanted one particular set of data to have labels on the points. And it was as easy as placing a conditional statement on the 'draw' event emitter... 

Now I'm playing around with the idea of placing legends close to each of the curves.

**Comment by juanomoran** [comment]
Done, I use the data.x and data.y to place the legend for the GOAL line

![image](https://cloud.githubusercontent.com/assets/6273090/6242138/e420e2c8-b707-11e4-98fa-f0ce9101e2ab.png)

**Comment by gionkunz** [comment]
Cool! :-) glad it worked out for you nicely.

**Comment by dmbf29** [comment]
The README never got changed FYI. Thankfully stumbled across this issue. Although no more errors, just labels aren't being displayed now 🤔

**Comment by Thaurin** [comment]
Same here, README is still wrong. Confused me a bit.
