### ISSUE TITLE
Possible for Bar chart?

### ISSUE THREAD

**Issue by jehad1990** [gionkunz/chartist-plugin-pointlabels#7]
I have a website which shows the progress of projects.

I really need to add the point labels but I only use Bar charts, is it possible to customize this plugin to work with Bar chart?

**Comment by artiswilliams** [comment]
The patch associated with this pull request adds this functionality: https://github.com/gionkunz/chartist-plugin-pointlabels/pull/8

You'll need to use the labelOffset and textAnchor to position it correctly depending on the type of bar chart you have.

**Comment by scorredoira** [comment]
@artiswilliams I had to change data.value.x to .y to make it work:

` options.labelInterpolationFnc(data.value.y === undefined ? '' : data.value.y));`
